### ISSUE TITLE
Entity sensor.kitchen_config_timestamp cannot be added as the entity category is set to config

### ISSUE THREAD

**Issue by redneckdba** [siku2/hass-dingz#40]
Hi,
First of all thanks a lot for this component, it really made my dingz integeation into HA a lot easier!
It seems that the dingz component fails to load after upgrading to HA 2023.11.2 with the following error below.
According to https://github.com/home-assistant/core/issues/103192 this seems to be a known issue as removig the config.timestamp sensor from sensors.py fixed it and the component then loads successfully again.

`2023-11-10 19:02:13.098 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up dingz platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 367, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1021, in add_to_platform_finish
    await self.async_internal_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 279, in async_internal_added_to_hass
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: Entity sensor.kitchen_config_timestamp cannot be added as the entity category is set to config`

Thanks

**Comment by siku2** [comment]
Fixed in 0.5.0
